export const mentionUserList = 
    [
        {
            "user_uuid": "622bf145-f1cb-408b-8400-0995edf7eb39",
            "user_email": "adrianasantos@frstfalconi.com",
            "slug": "adrianasantosfrstfalconicom",
            "name": "Adriana Maria Dos Santos",
            "profile": {
                "uuid": "622bf145-f1cb-408b-8400-0995edf7eb39",
                "first_name": "Adriana",
                "last_name": "Maria Dos Santos",
                "email": "adrianasantos@frstfalconi.com",
                "phone": "(22) 22222-2222",
                "language": "pt-br",
                "avatar": "https://api-deimos.s3.amazonaws.com/86f3560bd84026011576-Copia_de_Tutorial__Como_fazer_um_avatar_FRST_1.png",
                "profession": "",
                "linkedin": "",
                "theme_color": "",
                "theme_type": "",
                "bio": "",
                "area_uuid": "78da5040-e393-4ae7-b6f7-c8aafbe045a0",
                "area_name": "Outro",
                "role_uuid": "1aa1ef3b-c9d1-4bf6-af34-d531f312fb07",
                "role_name": "Outro(a)",
                "company_uuid": "b1005836-b0a6-4a50-8147-537ebdc64a75",
                "company_name": "FRST   FALCONI ROAD OF SKILLS AND TALENTS TREINAMENTO E DESENVOLVIMENTO DE PESSOAS LTDA."
            }
        },
        {
            "user_uuid": "017f2779-d6cd-4343-916f-f85b7e1f2faa",
            "user_email": "a.camargo.m12@gmail.com",
            "slug": "acamargom12gmailcom",
            "name": "Alexandre Camargo",
            "profile": {
                "uuid": "017f2779-d6cd-4343-916f-f85b7e1f2faa",
                "first_name": "Alexandre",
                "last_name": "Camargo",
                "email": "a.camargo.m12@gmail.com",
                "phone": "(11) 94658-5608",
                "language": "pt-br",
                "avatar": "https://api-deimos.s3.amazonaws.com/3b5df41ff0a427fdc437-WhatsApp-Image-2022-04-25-at-08.33.50.jpeg",
                "profession": "",
                "linkedin": "",
                "theme_color": "",
                "theme_type": "",
                "bio": "",
                "area_uuid": "78da5040-e393-4ae7-b6f7-c8aafbe045a0",
                "area_name": "Outro",
                "role_uuid": "1aa1ef3b-c9d1-4bf6-af34-d531f312fb07",
                "role_name": "Outro(a)",
                "company_uuid": "b1005836-b0a6-4a50-8147-537ebdc64a75",
                "company_name": "FRST   FALCONI ROAD OF SKILLS AND TALENTS TREINAMENTO E DESENVOLVIMENTO DE PESSOAS LTDA."
            }
        },
        {
            "user_uuid": "47167c9a-a485-4b13-86bc-35eab0dd8540",
            "user_email": "alexandremoraes@frstfalconi.com",
            "slug": "alexandremoraesfrstfalconicom",
            "name": "Alexandre Camargo",
            "profile": {
                "uuid": "47167c9a-a485-4b13-86bc-35eab0dd8540",
                "first_name": "Alexandre",
                "last_name": "Camargo",
                "email": "alexandremoraes@frstfalconi.com",
                "phone": "(99) 99999-10001",
                "language": "pt-br",
                "avatar": "",
                "profession": "",
                "linkedin": "",
                "theme_color": "",
                "theme_type": "",
                "bio": "",
                "area_uuid": "0ddbba56-0182-4365-abb2-44a0d3873869",
                "area_name": "Vendas/Comercial",
                "role_uuid": "1aa1ef3b-c9d1-4bf6-af34-d531f312fb07",
                "role_name": "Outro(a)",
                "company_uuid": "b1005836-b0a6-4a50-8147-537ebdc64a75",
                "company_name": "FRST   FALCONI ROAD OF SKILLS AND TALENTS TREINAMENTO E DESENVOLVIMENTO DE PESSOAS LTDA."
            }
        },
        {
            "user_uuid": "0b038b6e-d69d-419b-b0fa-f3dee379aa85",
            "user_email": "alexsandersiqueira@frstfalconi.com",
            "slug": "alexsandertech",
            "name": "Alexsander Siqueira",
            "profile": {
                "uuid": "0b038b6e-d69d-419b-b0fa-f3dee379aa85",
                "first_name": "Alexsander",
                "last_name": "Siqueira",
                "email": "alexsandersiqueira@frstfalconi.com",
                "phone": "(99) 99999-1001",
                "language": "en-us",
                "avatar": "https://api-deimos-cdn.dev.frstfalconi.cloud/avatar/ee23baee-0197-44d9-862f-703b71404882.jpeg",
                "profession": "Desenvolvedor",
                "linkedin": "https://www.linkedin.com/in/alexsandertech/",
                "theme_color": "1",
                "theme_type": "frst",
                "bio": "Bio",
                "area_uuid": "19d741dc-ce75-4a5c-97fd-5a8dfe2432d6",
                "area_name": "Tecnologia da Informação",
                "role_uuid": "1aa1ef3b-c9d1-4bf6-af34-d531f312fb07",
                "role_name": "Outro(a)",
                "company_uuid": "b1005836-b0a6-4a50-8147-537ebdc64a75",
                "company_name": "FRST   FALCONI ROAD OF SKILLS AND TALENTS TREINAMENTO E DESENVOLVIMENTO DE PESSOAS LTDA."
            }
        },
        {
            "user_uuid": "7340ca5c-b52b-4a46-8e3a-4371182afaa1",
            "user_email": "floraalmeida@frstfalconi.com",
            "slug": "floraalmeidafrstfalconicom",
            "name": "Aluno Frst_D09",
            "profile": {
                "uuid": "7340ca5c-b52b-4a46-8e3a-4371182afaa1",
                "first_name": "Aluno",
                "last_name": "Frst_D09",
                "email": "floraalmeida@frstfalconi.com",
                "phone": "(00) 00000-0000",
                "language": "pt-br",
                "avatar": "",
                "profession": "",
                "linkedin": "",
                "theme_color": "",
                "theme_type": "",
                "bio": "",
                "area_uuid": "78da5040-e393-4ae7-b6f7-c8aafbe045a0",
                "area_name": "Outro",
                "role_uuid": "1aa1ef3b-c9d1-4bf6-af34-d531f312fb07",
                "role_name": "Outro(a)",
                "company_uuid": "b1005836-b0a6-4a50-8147-537ebdc64a75",
                "company_name": "FRST   FALCONI ROAD OF SKILLS AND TALENTS TREINAMENTO E DESENVOLVIMENTO DE PESSOAS LTDA."
            }
        },
        {
            "user_uuid": "3affa079-b31e-45a6-9281-1cfbc6d4eb4b",
            "user_email": "ams.tecnica+guest@gmail.com",
            "slug": "amstecnicaguestgmailcom",
            "name": "Aluno Não Cadastrado",
            "profile": {
                "uuid": "3affa079-b31e-45a6-9281-1cfbc6d4eb4b",
                "first_name": "Aluno",
                "last_name": "Não Cadastrado",
                "email": "ams.tecnica+guest@gmail.com",
                "phone": "(00) 00000-0000",
                "language": "pt-br",
                "avatar": "",
                "profession": "",
                "linkedin": "",
                "theme_color": "",
                "theme_type": "",
                "bio": "",
                "area_uuid": "7e65c274-e8e5-424d-b961-ddbe3bbb6324",
                "area_name": "Alta Direção",
                "role_uuid": "38c0ac24-4d15-42ef-8f14-0d1ebcf6e93f",
                "role_name": "C-Level",
                "company_uuid": "b1005836-b0a6-4a50-8147-537ebdc64a75",
                "company_name": "FRST   FALCONI ROAD OF SKILLS AND TALENTS TREINAMENTO E DESENVOLVIMENTO DE PESSOAS LTDA."
            }
        },
        {
            "user_uuid": "050d7925-c7ad-43c1-b6ca-ba890e37cad2",
            "user_email": "anatolentino@frstfalconi.com",
            "slug": "anatolentinofrstfalconicom",
            "name": "Ana Paula Murta Tolentino",
            "profile": {
                "uuid": "050d7925-c7ad-43c1-b6ca-ba890e37cad2",
                "first_name": "Ana",
                "last_name": "Paula Murta Tolentino",
                "email": "anatolentino@frstfalconi.com",
                "phone": "(31) 99252-1152",
                "language": "pt-br",
                "avatar": "",
                "profession": "",
                "linkedin": "",
                "theme_color": "",
                "theme_type": "",
                "bio": "",
                "area_uuid": "0ddbba56-0182-4365-abb2-44a0d3873869",
                "area_name": "Vendas/Comercial",
                "role_uuid": "1aa1ef3b-c9d1-4bf6-af34-d531f312fb07",
                "role_name": "Outro(a)",
                "company_uuid": "b1005836-b0a6-4a50-8147-537ebdc64a75",
                "company_name": "FRST   FALCONI ROAD OF SKILLS AND TALENTS TREINAMENTO E DESENVOLVIMENTO DE PESSOAS LTDA."
            }
        },
        {
            "user_uuid": "65520b6d-781e-4598-bed9-3f352e675918",
            "user_email": "barbaramartins@frstfalconi.com",
            "slug": "barbaramartinsfrstfalconicom",
            "name": "Barbara",
            "profile": {
                "uuid": "65520b6d-781e-4598-bed9-3f352e675918",
                "first_name": "Barbara",
                "last_name": "",
                "email": "barbaramartins@frstfalconi.com",
                "phone": "(11) 98899-8827",
                "language": "pt-br",
                "avatar": "",
                "profession": "",
                "linkedin": "",
                "theme_color": "",
                "theme_type": "",
                "bio": "",
                "area_uuid": "0ddbba56-0182-4365-abb2-44a0d3873869",
                "area_name": "Vendas/Comercial",
                "role_uuid": "38c0ac24-4d15-42ef-8f14-0d1ebcf6e93f",
                "role_name": "C-Level",
                "company_uuid": "b1005836-b0a6-4a50-8147-537ebdc64a75",
                "company_name": "FRST   FALCONI ROAD OF SKILLS AND TALENTS TREINAMENTO E DESENVOLVIMENTO DE PESSOAS LTDA."
            }
        },
        {
            "user_uuid": "00e1e74a-65d5-4e35-aa05-d441736dcdf9",
            "user_email": "bellsalzstein@frstfalconi.com",
            "slug": "bellsalzsteinfrstfalconicom",
            "name": "Bell",
            "profile": {
                "uuid": "00e1e74a-65d5-4e35-aa05-d441736dcdf9",
                "first_name": "Bell",
                "last_name": "",
                "email": "bellsalzstein@frstfalconi.com",
                "phone": "(11) 98899-8900",
                "language": "pt-br",
                "avatar": "",
                "profession": "",
                "linkedin": "",
                "theme_color": "",
                "theme_type": "",
                "bio": "",
                "area_uuid": "0ddbba56-0182-4365-abb2-44a0d3873869",
                "area_name": "Vendas/Comercial",
                "role_uuid": "38c0ac24-4d15-42ef-8f14-0d1ebcf6e93f",
                "role_name": "C-Level",
                "company_uuid": "b1005836-b0a6-4a50-8147-537ebdc64a75",
                "company_name": "FRST   FALCONI ROAD OF SKILLS AND TALENTS TREINAMENTO E DESENVOLVIMENTO DE PESSOAS LTDA."
            }
        },
        {
            "user_uuid": "537b4672-0fa3-11ed-a5ac-02a719f30235",
            "user_email": "brunoaraujo@frstfalconi.com",
            "slug": "brunoaraujofrstfalconicom",
            "name": "Bruno Araujo",
            "profile": {
                "uuid": "537b4672-0fa3-11ed-a5ac-02a719f30235",
                "first_name": "Bruno",
                "last_name": "Araujo",
                "email": "brunoaraujo@frstfalconi.com",
                "phone": "(03) 99831-2861",
                "language": "pt-br",
                "avatar": "",
                "profession": "",
                "linkedin": "",
                "theme_color": "",
                "theme_type": "",
                "bio": "",
                "area_uuid": "e9b08864-0101-44fa-b54c-ff0392526fd0",
                "area_name": "Produto",
                "role_uuid": "c265667f-1aa8-4c3d-b315-933b74478c36",
                "role_name": "Analista",
                "company_uuid": "b1005836-b0a6-4a50-8147-537ebdc64a75",
                "company_name": "FRST   FALCONI ROAD OF SKILLS AND TALENTS TREINAMENTO E DESENVOLVIMENTO DE PESSOAS LTDA."
            }
        }
    ]

